using backend.Models;

namespace backend.SeedData
{
    public class seatData
    {
        public static seat[] seatSeedData()
        {
            return new seat[]
                {
                    //1
                    new seat{Id=1,name="ghế số 1",busId=1},
                    new seat{Id=2,name="ghế số 2",busId=1},
                    new seat{Id=3,name="ghế số 3",busId=1},
                    new seat{Id=4,name="ghế số 4",busId=1},
                    new seat{Id=5,name="ghế số 5",busId=1},
                    new seat{Id=6,name="ghế số 6",busId=1},
                    new seat{Id=7,name="ghế số 7",busId=1},
                    new seat{Id=8,name="ghế số 8",busId=1},
                    new seat{Id=9,name="ghế số 9",busId=1},
                    new seat{Id=10,name="ghế số 10",busId=1},
                    new seat{Id=11,name="ghế số 11",busId=1},
                    new seat{Id=12,name="ghế số 12",busId=1},
                    new seat{Id=13,name="ghế số 13",busId=1},
                    new seat{Id=14,name="ghế số 14",busId=1},
                    new seat{Id=15,name="ghế số 15",busId=1},
                    new seat{Id=16,name="ghế số 16",busId=1},
                    //2
                    new seat{Id=17,name="ghế số 1",busId=2},
                    new seat{Id=18,name="ghế số 2",busId=2},
                    new seat{Id=19,name="ghế số 3",busId=2},
                    new seat{Id=20,name="ghế số 4",busId=2},
                    new seat{Id=21,name="ghế số 5",busId=2},
                    new seat{Id=22,name="ghế số 6",busId=2},
                    new seat{Id=23,name="ghế số 7",busId=2},
                    new seat{Id=24,name="ghế số 8",busId=2},
                    new seat{Id=25,name="ghế số 9",busId=2},
                    new seat{Id=26,name="ghế số 10",busId=2},
                    new seat{Id=27,name="ghế số 11",busId=2},
                    new seat{Id=28,name="ghế số 12",busId=2},
                    new seat{Id=29,name="ghế số 13",busId=2},
                    new seat{Id=30,name="ghế số 14",busId=2},
                    new seat{Id=31,name="ghế số 15",busId=2},
                    new seat{Id=32,name="ghế số 16",busId=2},
                        //3
                    new seat{Id=33,name="ghế số 1",busId=3},
                    new seat{Id=34,name="ghế số 2",busId=3},
                    new seat{Id=35,name="ghế số 3",busId=3},
                    new seat{Id=36,name="ghế số 4",busId=3},
                    new seat{Id=37,name="ghế số 5",busId=3},
                    new seat{Id=38,name="ghế số 6",busId=3},
                    new seat{Id=39,name="ghế số 7",busId=3},
                    new seat{Id=40,name="ghế số 8",busId=3},
                    new seat{Id=41,name="ghế số 9",busId=3},
                    new seat{Id=42,name="ghế số 10",busId=3},
                    new seat{Id=43,name="ghế số 11",busId=3},
                    new seat{Id=44,name="ghế số 12",busId=3},
                    new seat{Id=45,name="ghế số 13",busId=3},
                    new seat{Id=46,name="ghế số 14",busId=3},
                    new seat{Id=47,name="ghế số 15",busId=3},
                    new seat{Id=48,name="ghế số 16",busId=3},
                        //4
                    /*new seat{Id=49,name="ghế số 1",busId=4},
                    new seat{Id=50,name="ghế số 2",busId=4},
                    new seat{Id=51,name="ghế số 3",busId=4},
                    new seat{Id=52,name="ghế số 4",busId=4},
                    new seat{Id=53,name="ghế số 5",busId=4},
                    new seat{Id=54,name="ghế số 6",busId=4},
                    new seat{Id=55,name="ghế số 7",busId=4},
                    new seat{Id=56,name="ghế số 8",busId=4},
                    new seat{Id=57,name="ghế số 9",busId=4},
                    new seat{Id=58,name="ghế số 10",busId=4},
                    new seat{Id=59,name="ghế số 11",busId=4},
                    new seat{Id=60,name="ghế số 12",busId=4},
                    new seat{Id=61,name="ghế số 13",busId=4},
                    new seat{Id=62,name="ghế số 14",busId=4},
                    new seat{Id=63,name="ghế số 15",busId=4},
                    new seat{Id=64,name="ghế số 16",busId=4},
                        //5
                    new seat{Id=65,name="ghế số 1",busId=5},
                    new seat{Id=66,name="ghế số 2",busId=5},
                    new seat{Id=67,name="ghế số 3",busId=5},
                    new seat{Id=68,name="ghế số 4",busId=5},
                    new seat{Id=69,name="ghế số 5",busId=5},
                    new seat{Id=70,name="ghế số 6",busId=5},
                    new seat{Id=71,name="ghế số 7",busId=5},
                    new seat{Id=72,name="ghế số 8",busId=5},
                    new seat{Id=73,name="ghế số 9",busId=5},
                    new seat{Id=74,name="ghế số 10",busId=5},
                    new seat{Id=75,name="ghế số 11",busId=5},
                    new seat{Id=76,name="ghế số 12",busId=5},
                    new seat{Id=77,name="ghế số 13",busId=5},
                    new seat{Id=78,name="ghế số 14",busId=5},
                    new seat{Id=79,name="ghế số 15",busId=5},
                    new seat{Id=80,name="ghế số 16",busId=5},
                        //6
                    new seat{Id=81,name="ghế số 1",busId=6},
                    new seat{Id=82,name="ghế số 2",busId=6},
                    new seat{Id=83,name="ghế số 3",busId=6},
                    new seat{Id=84,name="ghế số 4",busId=6},
                    new seat{Id=85,name="ghế số 5",busId=6},
                    new seat{Id=86,name="ghế số 6",busId=6},
                    new seat{Id=87,name="ghế số 7",busId=6},
                    new seat{Id=88,name="ghế số 8",busId=6},
                    new seat{Id=89,name="ghế số 9",busId=6},
                    new seat{Id=90,name="ghế số 10",busId=6},
                    new seat{Id=91,name="ghế số 11",busId=6},
                    new seat{Id=92,name="ghế số 12",busId=6},
                    new seat{Id=93,name="ghế số 13",busId=6},
                    new seat{Id=94,name="ghế số 14",busId=6},
                    new seat{Id=95,name="ghế số 15",busId=6},
                    new seat{Id=96,name="ghế số 16",busId=6},
                        //7
                    new seat{Id=97,name="ghế số 1",busId=7},
                    new seat{Id=98,name="ghế số 2",busId=7},
                    new seat{Id=99,name="ghế số 3",busId=7},
                    new seat{Id=100,name="ghế số 4",busId=7},
                    new seat{Id=101,name="ghế số 5",busId=7},
                    new seat{Id=102,name="ghế số 6",busId=7},
                    new seat{Id=103,name="ghế số 7",busId=7},
                    new seat{Id=104,name="ghế số 8",busId=7},
                    new seat{Id=105,name="ghế số 9",busId=7},
                    new seat{Id=106,name="ghế số 10",busId=7},
                    new seat{Id=107,name="ghế số 11",busId=7},
                    new seat{Id=108,name="ghế số 12",busId=7},
                    new seat{Id=109,name="ghế số 13",busId=7},
                    new seat{Id=110,name="ghế số 14",busId=7},
                    new seat{Id=111,name="ghế số 15",busId=7},
                    new seat{Id=112,name="ghế số 16",busId=7},
                        //8
                    new seat{Id=113,name="ghế số 1",busId=8},
                    new seat{Id=114,name="ghế số 2",busId=8},
                    new seat{Id=115,name="ghế số 3",busId=8},
                    new seat{Id=116,name="ghế số 4",busId=8},
                    new seat{Id=117,name="ghế số 5",busId=8},
                    new seat{Id=118,name="ghế số 6",busId=8},
                    new seat{Id=119,name="ghế số 7",busId=8},
                    new seat{Id=120,name="ghế số 8",busId=8},
                    new seat{Id=121,name="ghế số 9",busId=8},
                    new seat{Id=122,name="ghế số 10",busId=8},
                    new seat{Id=123,name="ghế số 11",busId=8},
                    new seat{Id=124,name="ghế số 12",busId=8},
                    new seat{Id=125,name="ghế số 13",busId=8},
                    new seat{Id=126,name="ghế số 14",busId=8},
                    new seat{Id=127,name="ghế số 15",busId=8},
                    new seat{Id=128,name="ghế số 16",busId=8},
                        //9
                    new seat{Id=129,name="ghế số 1",busId=9},
                    new seat{Id=130,name="ghế số 2",busId=9},
                    new seat{Id=131,name="ghế số 3",busId=9},
                    new seat{Id=132,name="ghế số 4",busId=9},
                    new seat{Id=133,name="ghế số 5",busId=9},
                    new seat{Id=134,name="ghế số 6",busId=9},
                    new seat{Id=135,name="ghế số 7",busId=9},
                    new seat{Id=136,name="ghế số 8",busId=9},
                    new seat{Id=137,name="ghế số 9",busId=9},
                    new seat{Id=138,name="ghế số 10",busId=9},
                    new seat{Id=139,name="ghế số 11",busId=9},
                    new seat{Id=140,name="ghế số 12",busId=9},
                    new seat{Id=141,name="ghế số 13",busId=9},
                    new seat{Id=142,name="ghế số 14",busId=9},
                    new seat{Id=143,name="ghế số 15",busId=9},
                    new seat{Id=144,name="ghế số 16",busId=9},
                        //10
                    new seat{Id=145,name="ghế số 1",busId=10},
                    new seat{Id=146,name="ghế số 2",busId=10},
                    new seat{Id=147,name="ghế số 3",busId=10},
                    new seat{Id=148,name="ghế số 4",busId=10},
                    new seat{Id=149,name="ghế số 5",busId=10},
                    new seat{Id=150,name="ghế số 6",busId=10},
                    new seat{Id=151,name="ghế số 7",busId=10},
                    new seat{Id=152,name="ghế số 8",busId=10},
                    new seat{Id=153,name="ghế số 9",busId=10},
                    new seat{Id=154,name="ghế số 10",busId=10},
                    new seat{Id=155,name="ghế số 11",busId=10},
                    new seat{Id=156,name="ghế số 12",busId=10},
                    new seat{Id=157,name="ghế số 13",busId=10},
                    new seat{Id=158,name="ghế số 14",busId=10},
                    new seat{Id=159,name="ghế số 15",busId=10},
                    new seat{Id=160,name="ghế số 16",busId=10},
*/

                };
        }
    }
}
