export const GET_BUS_LIST = "GET_BUS_LIST";
export const GET_ENABLE_BUS_LIST = "GET_ENABLE_BUS_LIST";
export const GET_BUS_DETAIL = "GET_BUS_DETAIL";
export const GET_BUS_TYPE_LIST = "GET_BUS_TYPE_LIST";
export const GET_BUS_TYPE_DETAIL = "GET_BUS_TYPE_DETAIL";

export const GET_DRIVER_LIST = "GET_DRIVER_LIST";
export const GET_REGISTER_DRIVER_LIST = "GET_REGISTER_DRIVER_LIST";
export const GET_DRIVER_DETAIL = "GET_DRIVER_DETAIL";

export const GET_STATION_LIST = "GET_STATION_LIST";
export const GET_STATION_DETAIL = "GET_STATION_DETAIL";

export const GET_TRIP_LIST = "GET_TRIP_LIST";
export const GET_TRIP_DETAIL = "GET_TRIP_DETAIL";

// News
export const GET_NEWS_LIST = "GET_NEWS_LIST";
export const GET_NEWS_DETAIL ="GET_NEWS_DETAIL";

export const GET_PROMOTE_TRIP_LIST = "GET_PROMOTE_TRIP_LIST";
export const GET_PROMOTE_TRIP_DETAIL = "GET_PROMOTE_TRIP_DETAIL";

export const LOGIN_ACTION = "LOGIN_ACTION";
export const REGISTER_ACTION = "REGISTER_ACTION";
export const LAY_LAI_MAT_KHAU_ACTION = "LAY_LAI_MAT_KHAU_ACTION";

export const GET_USER_LIST = "GET_USER_LIST";
export const GET_USER_DETAIL = "GET_USER_DETAIL";
export const GET_CURRENT_USER_ACTION = "GET_CURRENT_USER_ACTION";
export const GET_PROFILE_DETAIL = "GET_PROFILE_DETAIL";
export const TIM_KIEM_NGUOI_DUNG = "TIM_KIEM_NGUOI_DUNG";

export const GET_MOD_LIST = "GET_MOD_LIST";
export const GET_MOD_DETAIL = "GET_MOD_DETAIL";

export const GET_FAQ_LIST = "GET_FAQ_LIST";
export const GET_FAQ_DETAIL = "GET_FAQ_DETAIL";

export const CHON_GHE = "CHON_GHE";
export const ORDER_CONFIRM = "ORDER_CONFIRM";
export const DAT_VE = "DAT_VE";
export const DELETE_SELECTING_SEATS = "DELETE_SELECTING_SEATS";
export const GET_TICKET_RESULT = "GET_TICKET_RESULT";
export const GET_TICKET_BY_USER = "GET_TICKET_BY_USER";
export const GET_TICKET_BY_CUSTOMER = "GET_TICKET_BY_CUSTOMER";
export const GET_TICKET_STATUS = "GET_TICKET_STATUS";


export const GET_PROFIT_BY_ROUTE = "GET_PROFIT_BY_ROUTE";
export const GET_PROFIT_BY_MONTH = "GET_PROFIT_BY_MONTH";

export const DISPLAY_LOADING = "DISPLAY_LOADING";
export const HIDE_LOADING = "HIDE_LOADING";

export const CHUYEN_TAB = "CHUYEN_TAB";
export const CHUYEN_TAB_ACTIVE = "CHUYEN_TAB_ACTIVE";

